language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rahul61177/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahul61177/docker-react npm run test